accounts:
- users:
  - expires_in: "1625091954"
    password: litmus
    token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjUwOTE5NTQsInJvbGUiOiJ1c2VyIiwidWlkIjoiNzdkZTA3ZjctYzUwNi00YjFlLTkzMDYtZWQwOWIyZDBkOWI1IiwidXNlcm5hbWUiOiJyYWoifQ.zhSZXtMnCQ_AqeMzIkkGGU02p72FSA7s2oqthEcmGEwx-X_zfRHBsd5Npfh5COOGyq2H6BdCBSLZ-B6KOSQWcQ
    username: raj
  endpoint: https://litmus.preview.chaosnative.com
apiVersion: v1
current-account: https://litmus.preview.chaosnative.com
current-user: raj
kind: Config
