---
name: "\U0001F41B Bug report"
about: Create a report to help improve the project
title: ''
labels: bug
assignees: ''

---

<!--
  Thanks for filing an issue! Before hitting the button, please answer these questions.

  Fill in as much of the template below as you can.
  If you leave out information, we can't help you as well.

  Be ready for followup questions, and please respond in a timely
  manner. If we can't reproduce a bug we might close your issue.
  If we're wrong, PLEASE feel free to reopen it and explain why.
-->

**What happened**:

**What you expected to happen**:

**Where can this issue be corrected? (optional)**
<!-- provide additional information about the file location or directory that needs to be modified to fix this issue, if available -->

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: