name: Build CLI binaries

# This workflow will run on all branches
on:
  push:
    branches:
      - "*"
  # TODO - build binary for pull requests targeting master branch
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: branch_name

      - name: Build binaries
        uses: sosedoff/actions/golang-build@master
        env:
          COMPRESS_FILES: "true"